import { Client } from 'pg';

const init = async DB_URI => {
  const testClient = new Client(DB_URI);
  await testClient.connect();
  const userTestQuery = await testClient.query('SELECT * FROM users;');
  if (userTestQuery.rows) {
    return;
  }

  const client = new Client(DB_URI);
  await client.connect();
  const userQuery = await client.query(`
    CREATE TABLE users (
      user_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
      email varchar(255) NOT NULL,
      password varchar(255) NOT NULL
    );
  `);
  userQuery.rows.forEach(row => {
    console.log(row);
  });
  await client.end();

  const anotherClient = new Client(DB_URI);
  await anotherClient.connect();
  const orderQuery = await anotherClient.query(`
    CREATE TABLE orders (
      user_id smallint NOT NULL,
      order_id smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
      password varchar(255) NOT NULL
    );
  `);
  orderQuery.rows.forEach(row => {
    console.log(row);
  });
  await anotherClient.end();
}

// const initUsersTable = client.query(`
//   CREATE TABLE users (
//     user_id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
//     email VARCHAR(255) NOT NULL,
//     password VARCHAR(255) NOT NULL
//   );
// `);

// const initOrdersTable = async () => client.query(`
//   CREATE TABLE orders (
//     user_id SMALLINT AUTO_INCREMENT NOT NULL FOREIGN KEY,
//     order_id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
//     password
//   );
// `);

export default init;